event/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EventViewSet, EventMemberViewSet

router = DefaultRouter()
router.register(r'events', EventViewSet, basename='events')
router.register(r'events/(?P<event_id>[^/.]+)/members', EventMemberViewSet, basename='event-members')

urlpatterns = [
    path('', include(router.urls)),
]

ipr_app/urls.py
from django.contrib import admin
from django.urls import path, include

from account.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('social_group.urls')),
    path('', include('event.urls')),
    # ... other patterns ...
]

social_group/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('social-groups/', SocialGroupsView.as_view(), name='social_groups'),
    path('social-groups/<int:pk>/', SocialGroupDetailView.as_view(), name='social_group_detail'),
    path('social-groups/<int:social_group_id>/users', SocialGroupUsersView.as_view(), name='social_group_memebers'),
    path('social-groups/create/', CreateSocialGroupView.as_view(), name='create_social_group'),
    path('join-group/<int:group_id>/', JoinGroupView.as_view(), name='join_group'),
    path('social-groups/<int:social_group_id>/add-post/', AddPostView.as_view(), name='social_group_add_post'),
    path('social-groups/<int:post_id>/add-comment/', AddCommentView.as_view(), name='social_group_add_comment'),
    path('edit-comment/', EditCommentView.as_view(), name='social_group_edit_comment'),
    path('social-groups/post/<int:post_id>/delete/', DeletePostView.as_view(), name='social_group_delete_post'),
    path('edit-post/<int:post_id>/', EditPostView.as_view(), name='edit_post'),
    path('add-comment/<int:post_id>/', AddCommentView.as_view(), name='add_comment'),
    path('social-groups/<int:social_group_id>/<int:user_id>/invite-user/', InviteUserView.as_view(),
         name='invite_user'),
    path('social-groups/<int:social_group_id>/events/', SocialGroupEventsView.as_view(), name='social_group_events'),
    path('social-groups/<int:social_group_id>/create-event/', CreateSocialGroupEventView.as_view(),
         name='create_social_group_event'),
    path('social-groups/<int:social_group_id>/events/<int:event_id>/join/', JoinEventView.as_view(), name='join_event'),
    path('social-groups/<int:social_group_id>/events/<int:event_id>/delete/', DeleteEventView.as_view(),
         name='delete_event'),
    path('social-groups/<int:social_group_id>/leave/', LeaveGroupView.as_view(), name='leave_group'),
    path('delete-group/<int:group_id>/', DeleteGroupView.as_view(), name='delete_group'),

    path('social-groups/<int:social_group_id>/posts/<int:post_id>/report', SocialGroupPostReportView.as_view(),
         name='report-post'),
    path('post/<int:post_id>/comment/<int:comment_id>', PostCommentReport.as_view(), name='report_comment'),
    path('delete-comment/<int:comment_id>/', DeleteCommentView.as_view(), name='delete_comment'),

]

social_group/models.py
from django.db import models
from django.conf import settings


class SocialGroupMember(models.Model):
    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('moderator', 'Moderator'),
        ('member', 'Member'),
    )
    social_group = models.ForeignKey('SocialGroup', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='social_group_members', on_delete=models.CASCADE, null=False,
                             blank=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    date_left = models.DateTimeField(null=True, blank=True)
    role = models.CharField(max_length=50, null=False, blank=False, choices=ROLE_CHOICES)


class SocialGroup(models.Model):
    PRIVACY_CHOICES = (
        ('public', 'Public'),
        ('private', 'Private'),
    )

    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    privacy = models.CharField(max_length=7, choices=PRIVACY_CHOICES, default='public')


class SocialGroupPost(models.Model):
    social_group = models.ForeignKey(SocialGroup, related_name='posts', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='social_group_posts', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    media = models.FileField(upload_to='social_group_posts/', null=True, blank=True)

    def __str__(self):
        return f"Post by {self.user.first_name} {self.user.last_name} in {self.social_group.name} at {self.created_at.strftime('%Y-%m-%d %H:%M')}"

    class Meta:
        ordering = ['-created_at']


class Comment(models.Model):
    post = models.ForeignKey(SocialGroupPost, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Comment by {self.user.get_full_name()} on {self.created_at.strftime('%Y-%m-%d %H:%M')}"

    class Meta:
        ordering = ['created_at']


class SocialGroupEvent(models.Model):
    TOURNAMENT_CHOICES = (
        ('no', 'No Tournament'),
        ('individual', 'Individual Tournament'),
        ('team', 'Team Tournament'),
    )

    social_group = models.ForeignKey('SocialGroup', related_name='events', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    budget = models.DecimalField(max_digits=10, decimal_places=2,
                                 default=0.00)  # Możesz dostosować max_digits i decimal_places
    sponsors = models.TextField(blank=True, null=True)  # Długi string do przechowywania informacji o sponsorach
    is_tournament = models.CharField(max_length=10, choices=TOURNAMENT_CHOICES, default='no')

    def __str__(self):
        return f"{self.name} in {self.social_group.name}"

    class Meta:
        ordering = ['-id']  # Zakładam, że chcesz sortować wydarzenia według najnowszych. Możesz to zmienić.


class SocialGroupEventMember(models.Model):
    ROLE_CHOICES = (
        ('participant', 'Participant'),
        ('organizer', 'Organizer'),
        ('spectator', 'Spectator'),
    )

    event = models.ForeignKey(SocialGroupEvent, related_name='members', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='event_memberships', on_delete=models.CASCADE)
    date_joined = models.DateTimeField(auto_now_add=True)
    role = models.CharField(max_length=50, choices=ROLE_CHOICES)

    def __str__(self):
        return f"{self.user.get_full_name()} - {self.role} in {self.event.name}"

social_group/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormMixin

from account.models import Notification
from account.models import User
from .forms import CommentForm
from .forms import SocialGroupEventForm
from .forms import SocialGroupForm
from .forms import SocialGroupPostForm
from .models import Comment
from .models import SocialGroup
from .models import SocialGroupEvent, SocialGroupEventMember
from .models import SocialGroupMember
from .models import SocialGroupPost


class SocialGroupsView(View):
    template_name = 'social_groups.html'

    def get(self, request, *args, **kwargs):
        search_my_groups = request.GET.get('search_my_groups', '')
        search_all_groups = request.GET.get('search_all_groups', '')

        # Get the complete list of group IDs for groups the user is a member of
        all_user_group_ids = SocialGroupMember.objects.filter(
            user=request.user
        ).values_list('social_group__id', flat=True)

        # User Groups with search functionality
        user_groups_query = Q(user=request.user)
        if search_my_groups:
            user_groups_query &= Q(social_group__name__icontains=search_my_groups)
        user_groups = SocialGroupMember.objects.filter(user_groups_query).select_related('social_group')

        # All Public Groups excluding user's groups with search functionality
        all_groups_query = Q(privacy='public')
        if search_all_groups:
            all_groups_query &= Q(name__icontains=search_all_groups)
        all_groups = SocialGroup.objects.filter(all_groups_query).exclude(id__in=all_user_group_ids)

        context = {
            'user_groups': [member.social_group for member in user_groups],
            'all_groups': all_groups
        }

        return render(request, self.template_name, context)


class CreateSocialGroupView(LoginRequiredMixin, CreateView):
    model = SocialGroup
    form_class = SocialGroupForm
    template_name = 'create_social_group.html'
    success_url = reverse_lazy('social_groups')  # Zaktualizuj, jeśli potrzebujesz innego URL

    def form_valid(self, form):
        form.instance.creator = self.request.user  # Zakładam, że masz pole 'creator' w modelu SocialGroup
        response = super().form_valid(form)  # Zapisz grupę
        # Dodaj użytkownika jako członka grupy z rolą 'admin'
        SocialGroupMember.objects.create(user=self.request.user, social_group=self.object, role='admin')
        return response


class JoinGroupView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        group_id = self.kwargs['group_id']
        group = get_object_or_404(SocialGroup, pk=group_id)
        # Sprawdź, czy użytkownik już nie jest członkiem grupy
        if not SocialGroupMember.objects.filter(user=request.user, social_group=group).exists():
            SocialGroupMember.objects.create(user=request.user, social_group=group, role='member')
        return redirect('social_groups')  # Zakładam, że 'social_groups' to nazwa URL do Twojej listy grup


class SocialGroupDetailView(LoginRequiredMixin, FormMixin, DetailView):
    model = SocialGroup
    template_name = 'social_group_detail.html'
    context_object_name = 'social_group'
    form_class = SocialGroupPostForm  # Assuming you want to create a post from the detail view

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        social_group = self.get_object()

        # Get search query from the request
        search_query = self.request.GET.get('search_posts', '')

        # Filter posts based on the search query
        posts_query = Q(social_group=social_group)
        if search_query:
            posts_query &= (Q(user__first_name__icontains=search_query) |
                            Q(user__last_name__icontains=search_query) |
                            Q(content__icontains=search_query))
        posts = SocialGroupPost.objects.filter(posts_query).order_by('-created_at')

        context['posts'] = posts
        context['search_posts'] = search_query
        context['comment_form'] = CommentForm()  # For adding comments
        context['current_group_id'] = social_group.id
        self.request.session["current_group_id"] = social_group.id

        # Find the admin member of the social group
        user_membership = SocialGroupMember.objects.filter(
            user=self.request.user,
            social_group=social_group
        ).first()
        context['user_is_admin_or_moderator'] = user_membership.role in ['admin',
                                                                         'moderator'] if user_membership else False

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()  # Get the social group
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.social_group = self.get_object()
        post.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('social_group_detail', kwargs={'pk': self.object.pk})


class AddPostView(CreateView):
    model = SocialGroupPost
    form_class = SocialGroupPostForm
    template_name = 'create_post_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['social_group_id'] = self.kwargs['social_group_id']  # Ensure this key matches your URL conf
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.social_group_id = self.kwargs['social_group_id']
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('social_group_detail', kwargs={'pk': self.kwargs['social_group_id']})


class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = get_object_or_404(SocialGroupPost, pk=post_id)
            comment.save()
            can_edit = request.user == comment.user or request.user.is_staff
            return JsonResponse({'status': 'success', 'comment_id': comment.id, 'comment': comment.content,
                                 'user': comment.user.get_full_name(), 'can_edit': can_edit})
        else:
            return JsonResponse({'status': 'error', 'errors': form.errors})


@method_decorator(csrf_exempt, name='dispatch')
class EditCommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        comment_id = data.get('id')
        content = data.get('content')

        try:
            comment = Comment.objects.get(pk=comment_id, user=request.user)  # Tylko autor może edytować komentarz
            comment.content = content
            comment.save()
            return JsonResponse({'status': 'success', 'content': content})
        except Comment.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Comment not found or permission denied'}, status=404)


class DeletePostView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        post = get_object_or_404(SocialGroupPost, pk=kwargs['post_id'])
        if request.user == post.user or request.user.is_staff:
            post.delete()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error', 'message': 'You do not have permission to delete this post.'},
                                status=403)


@method_decorator(csrf_exempt, name='dispatch')
class EditPostView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        post = get_object_or_404(SocialGroupPost, pk=post_id)
        if request.user == post.user or request.user.is_staff:
            data = json.loads(request.body)
            post.content = data['content']
            post.save()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Not authorized to edit this post'}, status=403)


class SocialGroupUsersView(LoginRequiredMixin, View):
    template_name = 'social_group_users.html'

    def get(self, request, social_group_id):
        search_members = request.GET.get('search_members', '')
        search_non_members = request.GET.get('search_non_members', '')

        social_group = get_object_or_404(SocialGroup, pk=social_group_id)

        # Get the complete list of members in the group without search filter
        all_member_ids = SocialGroupMember.objects.filter(
            social_group=social_group
        ).values_list('user__id', flat=True)

        # Members of the group with search functionality
        members_query = Q(social_group=social_group)
        if search_members:
            members_query &= (
                    Q(user__first_name__icontains=search_members) |
                    Q(user__last_name__icontains=search_members)
            )

social_group/templates/create_post_form.html
{% extends 'social_group_base.html' %}

{% block content %}
    <div class="container mt-5">
        <h2>Create Post</h2>
        <form method="post" class="mt-3">
            {% csrf_token %}
            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                <textarea name="content" id="content" class="form-control" rows="3"
                          placeholder="Write Comment Here.">{{ form.content.value|default:"" }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary me-2">Create Post</button>
            <a href="{% url 'social_group_detail' pk=social_group_id %}" class="btn btn-secondary">Back to Group</a>
        </form>
    </div>
{% endblock %}

social_group/templates/create_social_group.html
{% extends 'base.html' %}
{% load static your_custom_filters %}  <!-- Dodaj 'form_filters' do listy ładowanych tagów szablonu -->
{% block content %}
<div class="container mt-3">
    <h2>Create New Social Group</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name</label>
            {{ form.name|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <label for="id_description">Description</label>
            {{ form.description|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <label>Privacy</label>
            {% for radio in form.privacy %}
    <div class="form-check">
        {{ radio.tag }}  <!-- Directly render the radio button tag -->
        <label class="form-check-label {{ radio.choice_value }}" for="{{ radio.id_for_label }}">
            {{ radio.choice_label }}
        </label>
    </div>
{% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Create Group</button>
    </form>
</div>
{% endblock %}

social_group/templates/create_social_group_event.html
{% extends 'social_group_base.html' %}

{% block content %}
    <div class="container">
        <h2>Create Event</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create Event</button>
        </form>
    </div>
    <div style="margin-top: 2rem"></div>
{% endblock %}

social_group/templates/social_group_base.html
<!-- base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}My Django App{% endblock %}</title>
  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link href="{% static 'custom/style.css' %}" rel="stylesheet" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js">
</script>

</head>
<body>

{% include 'social_group_navbar.html' %}

<div class="container">
  {% block content %}
  {% endblock %}
</div>

<!-- Bootstrap JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

social_group/templates/social_group_events.html
{% extends 'social_group_base.html' %}

{% block content %}
    <div class="container">
        <a href="{% url 'create_social_group_event' social_group_id=social_group_id %}" style="margin-top: 2rem;"
           class="btn btn-primary">Create
            Event</a>

        <h2 class="mt-4">My Events</h2>
        <ul class="list-group">
            {% for event in user_events %}
                <li class="list-group-item d-flex justify-content-between align-items-center"
                    data-toggle="modal" data-target="#eventModal{{ event.id }}"
                    style="cursor:pointer; background-color: #D0D0D0 !important;">
                <span>
                    {{ event.name }}
                </span>
                    <!-- Modal dla szczegółów wydarzenia -->
                    <div class="modal fade" id="eventModal{{ event.id }}" tabindex="-1" role="dialog"
                         aria-labelledby="eventModalLabel{{ event.id }}" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="eventModalLabel{{ event.id }}">{{ event.name }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        <strong>Description:</strong> {{ event.description|default:"No description provided." }}
                                    </p>
                                    <p><strong>Budget:</strong> {{ event.budget }}</p>
                                    <p><strong>Sponsors:</strong> {{ event.sponsors|default:"No sponsors." }}</p>
                                    <p><strong>Tournament:</strong> {{ event.get_is_tournament_display }}</p>
                                    <!-- Możesz dodać więcej szczegółów zgodnie z potrzebami -->
                                </div>
                                <div class="modal-footer">
                                    {% if event.is_organizer %}
                                        <form action="{% url 'delete_event' social_group_id=social_group_id event_id=event.id %}"
                                              method="post" class="event-action-form">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger btn-sm">Delete Event</button>
                                        </form>
                                    {% endif %}
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            {% empty %}
                <li class="list-group-item">No events found.</li>
            {% endfor %}
        </ul>

        <h2 class="mt-4">Available Events</h2>
        <ul class="list-group">
            {% for event in available_events %}
                <li class="list-group-item d-flex justify-content-between align-items-center"
                    style="background-color: #D0D0D0 !important;">
                <span data-toggle="modal" data-target="#availableEventModal{{ event.id }}" style="cursor:pointer;">
                    {{ event.name }} - {{ event.description }}
                </span>

                    <!-- Modal for event details -->
                    <div class="modal fade" id="availableEventModal{{ event.id }}" tabindex="-1" role="dialog"
                         aria-labelledby="availableEventModalLabel{{ event.id }}" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"
                                        id="availableEventModalLabel{{ event.id }}">{{ event.name }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        <strong>Description:</strong> {{ event.description|default:"No description provided." }}
                                    </p>
                                    <p><strong>Budget:</strong> {{ event.budget }}</p>
                                    <p><strong>Sponsors:</strong> {{ event.sponsors|default:"No sponsors." }}</p>
                                    <p><strong>Tournament:</strong> {{ event.get_is_tournament_display }}</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <form action="{% url 'join_event' social_group_id=social_group_id event_id=event.id %}"
                          method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-primary">Join Event</button>
                    </form>
                </li>
            {% empty %}
                <li class="list-group-item">No available events.</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

social_group/templates/social_group_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-success">
    <div class="container-fluid justify-content-between position-relative">
        <!-- Left Aligned - Brand and Toggler -->
        <div class="d-flex align-items-center">
            <a class="navbar-brand" href="/">Dashboard</a>
        </div>

        <!-- Centered Links -->
        <div class="collapse navbar-collapse justify-content-center center-md" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% if current_group_id %}{% url 'social_group_detail' pk=current_group_id %}{% endif %}">Social Group Main Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% if current_group_id %}{% url 'social_group_events' social_group_id=current_group_id %}{% endif %}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% if current_group_id %}{% url 'social_group_memebers' current_group_id %}{% endif %}">Users</a>
                </li>
            </ul>
        </div>

        <!-- Right Aligned Links -->
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav flex-grow-0 ml-auto">
                <a class="nav-item nav-link" href="{% url 'social_groups' %}">Social Groups</a>
                <a class="nav-item nav-link" href="/settings">User Settings</a>
                <a class="nav-item btn btn-outline-secondary btn-sm nav-link" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </div>
</nav>